// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4gRe-fEJIN0z1Ydnd_4jkRxVUphmTQ4',
    appId: '1:348234898492:web:0d14c53df5f5437123b739',
    messagingSenderId: '348234898492',
    projectId: 'climatezone-b63de',
    authDomain: 'climatezone-b63de.firebaseapp.com',
    storageBucket: 'climatezone-b63de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA5CUsbMOb8yKSQqoDO-mRhMQPqT70U2k',
    appId: '1:348234898492:android:b06e1e8abc29687923b739',
    messagingSenderId: '348234898492',
    projectId: 'climatezone-b63de',
    storageBucket: 'climatezone-b63de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOpd-9y3obS-oVXTnpE0pFQcTeJMhfvGY',
    appId: '1:348234898492:ios:366551df86005b1b23b739',
    messagingSenderId: '348234898492',
    projectId: 'climatezone-b63de',
    storageBucket: 'climatezone-b63de.firebasestorage.app',
    iosBundleId: 'com.example.climatezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOpd-9y3obS-oVXTnpE0pFQcTeJMhfvGY',
    appId: '1:348234898492:ios:366551df86005b1b23b739',
    messagingSenderId: '348234898492',
    projectId: 'climatezone-b63de',
    storageBucket: 'climatezone-b63de.firebasestorage.app',
    iosBundleId: 'com.example.climatezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX4gRe-fEJIN0z1Ydnd_4jkRxVUphmTQ4',
    appId: '1:348234898492:web:17b301a985a8b00d23b739',
    messagingSenderId: '348234898492',
    projectId: 'climatezone-b63de',
    authDomain: 'climatezone-b63de.firebaseapp.com',
    storageBucket: 'climatezone-b63de.firebasestorage.app',
  );
}
