// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsqp6C99t5hdWy0Wehw9oyCqERD4cYiOc',
    appId: '1:942516248731:web:a5e3bc065aeb93c175663e',
    messagingSenderId: '942516248731',
    projectId: 'smoketrace-khi',
    authDomain: 'smoketrace-khi.firebaseapp.com',
    databaseURL: 'https://smoketrace-khi-default-rtdb.firebaseio.com',
    storageBucket: 'smoketrace-khi.firebasestorage.app',
    measurementId: 'G-Q74EG0RM8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxqxDV8BJsfvHvQk16cefOQol1sTdkjVw',
    appId: '1:942516248731:android:3f98a7b5920cc1c575663e',
    messagingSenderId: '942516248731',
    projectId: 'smoketrace-khi',
    databaseURL: 'https://smoketrace-khi-default-rtdb.firebaseio.com',
    storageBucket: 'smoketrace-khi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAsQKMnFNJioFG_-ZX6rgYGYWRfgzL9_M',
    appId: '1:942516248731:ios:35c7810038b80f0d75663e',
    messagingSenderId: '942516248731',
    projectId: 'smoketrace-khi',
    databaseURL: 'https://smoketrace-khi-default-rtdb.firebaseio.com',
    storageBucket: 'smoketrace-khi.firebasestorage.app',
    iosBundleId: 'com.example.climatezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAsQKMnFNJioFG_-ZX6rgYGYWRfgzL9_M',
    appId: '1:942516248731:ios:35c7810038b80f0d75663e',
    messagingSenderId: '942516248731',
    projectId: 'smoketrace-khi',
    databaseURL: 'https://smoketrace-khi-default-rtdb.firebaseio.com',
    storageBucket: 'smoketrace-khi.firebasestorage.app',
    iosBundleId: 'com.example.climatezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsqp6C99t5hdWy0Wehw9oyCqERD4cYiOc',
    appId: '1:942516248731:web:c952ec341238dc0275663e',
    messagingSenderId: '942516248731',
    projectId: 'smoketrace-khi',
    authDomain: 'smoketrace-khi.firebaseapp.com',
    databaseURL: 'https://smoketrace-khi-default-rtdb.firebaseio.com',
    storageBucket: 'smoketrace-khi.firebasestorage.app',
    measurementId: 'G-GEX9Y1FT92',
  );
}
